### PR TITLE
Rename shed.yml to .shed.yml and Travis

### PR DESCRIPTION
**Pull request by lecorguille**

### CODE REVIEW

**Comment by pkrog** [comment]
Hi Gildas,

I don't know why you made those modifications, since the build of branch master is successful on travis.
Anyway, the shed.yml file must not be renamed, I use a different scheme to publish on the toolshed. I first create a directory with everything needed inside, and the push on the toolshed. This at this stage that the shed.yml is copied and renamed in .shed.yml. I do this because I have many other files and directories in my repos that do not concern the toolshed. I only want to put only the necessary files on the toolshed.

About the travis file, I was going to make those modifications myself today.

Pierrick

**Comment by lecorguille** [comment]
Originaly, I just wanted to add the update line in the .travis.yml
I didn't know for the shed.yml.
And I observed a mistake in your build.xml.

And NO, any of your travis test seem to pass if I trust the branch tab.

That's funny how you try to never accept my PR. I will soon think that it's on purpose. 😄

**Comment by pkrog** [comment]
Try again with a better pull request, and we will talk again about it :-)

**Comment by lecorguille** [comment]
I have a better idea: no more PR on CEA tools. 
Not a big deal. Now I'm aware of that. That way I will no more waste time :-)

You finally agreed with 2 modifications among 3. You could have just rename the .shed.yml within the branch and accept the rest. That's GitHub! Show that you are interesting in social development and do your best to help them to help you.

**Comment by pkrog** [comment]
Why do you always search conflict ? I don't get it. I have no time for that. I didn't know I could just modify one of the commit and accept the others, I thought it was like a bundle to accept as whole or to reject.
Anyway do as you wish, because I'm not interested in conflicts and that type of discussion.

**Comment by lecorguille** [comment]
Let put that on the fact you didn't know the system!

**Comment by pkrog** [comment]
Yes, please, I'm not against your PRs at all ! I thank you for your great work Gildas.

**Pull request closed without merging**
